var choo = require('choo')
var log = require('choo-log')
var apiService = require('./services/apiService')
var postService = require('./services/postService')
var commentService = require('./services/commentService')
var PostsPage = require('./pages/PostsPage')
var PostDetailsPage = require('./pages/PostDetailsPage')

var app = choo()
app.use(log())
app.use(apiService)
app.use(postService)
app.use(commentService)
app.route('/posts/:post', PostDetailsPage)
app.route('/', PostsPage)
app.mount('body')
